# -*- coding: utf-8 -*-
"""grafico2_matriz_isf_kmeans.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uTtMNq7z6EeYBHDABlx4a6kfqVpYQJmG
"""

import matplotlib.pyplot as plt
import numpy as np
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

# ==============================================================================
# BASE DE DADOS EMPÍRICA CONSOLIDADA (16 Países)
# Vetor de entrada:
# [0] Dissuasão Nuclear / Ogivas / Limiar Fático (0.00 a 0.30)
# [1] Espaço / Vetores Balísticos Orbitais (0.00 a 0.25)
# [2] Domínio Fabril de Turbinas / Códigos de 5ª Geração (0.00 a 0.33)
# [3] Escore WIPO Normalizado Min-Max (0.00 a 1.00)
# ==============================================================================
dados_paises = {
    # --------------------------------------------------------------------------
    # SOBERANIA PLENA (Tríade/Segundo Ataque + Ciclo Fabril + Espaço + Base Civil)
    # --------------------------------------------------------------------------
    'Estados Unidos':  [0.30, 0.25, 0.33, 1.00],
    'China':           [0.30, 0.25, 0.33, 0.85],
    'Rússia':          [0.30, 0.25, 0.33, 0.35],
    'França':          [0.30, 0.23, 0.28, 0.78],
    'Reino Unido':     [0.30, 0.21, 0.26, 0.88],
    'Índia':           [0.30, 0.22, 0.18, 0.46],

    # --------------------------------------------------------------------------
    # SOBERANIA RESILIENTE (Veto Existencial / Balística Soberana / WIPO Restrito)
    # --------------------------------------------------------------------------
    'Coreia do Norte': [0.30, 0.18, 0.00, 0.00],  # Ogivas e ICBMs de controle soberano exclusivo
    'Paquistão':       [0.30, 0.14, 0.02, 0.08],  # Ogivas ativas + mísseis Shaheen/Babur
    'Irã':             [0.18, 0.17, 0.02, 0.26],  # Limiar nuclear + supremacia balística regional

    # --------------------------------------------------------------------------
    # SOBERANIA TUTELADA (Alta Base Civil / Defesa Sob Fiador Hegemônico)
    # --------------------------------------------------------------------------
    'Coreia do Sul':   [0.00, 0.15, 0.10, 0.90],  # Tutela nuclear e comando dos EUA (OPCON)
    'Suíça':           [0.00, 0.00, 0.00, 1.00],  # Neutralidade blindada pelo entorno OTAN
    'Turquia':         [0.00, 0.12, 0.12, 0.45],  # Aliança OTAN / Bombas B61 dos EUA em Incirlik
    'Polônia':         [0.00, 0.06, 0.06, 0.42],  # Reequipamento maciço de prateleira sob abrigo OTAN

    # --------------------------------------------------------------------------
    # SOBERANIA CONDICIONADA (Autonomia Política / Gargalo em Turbinas e Motores)
    # --------------------------------------------------------------------------
    'Suécia':          [0.00, 0.10, 0.18, 0.92],  # Gripen / motor dependente de licença GE (EUA)
    'Brasil':          [0.00, 0.08, 0.08, 0.28],  # Programa Nuclear da Marinha e Embraer
    'Arábia Saudita':  [0.00, 0.00, 0.00, 0.35],  # Comprador de prateleira integral
    'Argentina':       [0.00, 0.06, 0.02, 0.24]   # Base de defesa com restrições orçamentárias
}

# Rotulagem ontológica de referência para convergência dos centróides
rotulos_alvo = {
    'Estados Unidos':  'Soberania Plena',
    'China':           'Soberania Plena',
    'Rússia':          'Soberania Plena',
    'França':          'Soberania Plena',
    'Reino Unido':     'Soberania Plena',
    'Índia':           'Soberania Plena',
    'Coreia do Norte': 'Soberania Resiliente',
    'Paquistão':       'Soberania Resiliente',
    'Irã':             'Soberania Resiliente',
    'Coreia do Sul':   'Soberania Tutelada',
    'Suíça':           'Soberania Tutelada',
    'Turquia':         'Soberania Tutelada',
    'Polônia':         'Soberania Tutelada',
    'Suécia':          'Soberania Condicionada',
    'Brasil':          'Soberania Condicionada',
    'Arábia Saudita':  'Soberania Condicionada',
    'Argentina':       'Soberania Condicionada'
}

nomes = list(dados_paises.keys())
X_plot = []

# ==============================================================================
# CÁLCULO DOS ÍNDICES (ISF 88/12 e Autonomia Militar Direta)
# ==============================================================================
for nome in nomes:
    v = dados_paises[nome]
    militar = v[0] + v[1] + v[2]
    wipo = v[3]

    # Eixo X: ISF Consolidado (88% Núcleo Militar Crítico + 12% WIPO Normalizado)
    isf = (0.88 * militar + 0.12 * wipo) * 100.0

    # Eixo Y: Autonomia Militar Dissuasória Direta (Núcleo Militar / 0.88 * 100)
    autonomia_militar = (militar / 0.88) * 100.0

    X_plot.append([isf, autonomia_militar])

X_plot = np.array(X_plot)

# ==============================================================================
# MACHINE LEARNING: K-MEANS ANCORADO POR BARICENTROS
# ==============================================================================
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_plot)

categorias_ordem = [
    'Soberania Plena',
    'Soberania Resiliente',
    'Soberania Condicionada',
    'Soberania Tutelada'
]

centroides_iniciais = []
for cat in categorias_ordem:
    indices = [i for i, nome in enumerate(nomes) if rotulos_alvo[nome] == cat]
    baricentro = np.mean(X_scaled[indices], axis=0)
    centroides_iniciais.append(baricentro)

centroides_iniciais = np.array(centroides_iniciais)

kmeans = KMeans(n_clusters=4, init=centroides_iniciais, n_init=1, random_state=42)
clusters = kmeans.fit_predict(X_scaled)

cluster_para_rotulo = {i: cat for i, cat in enumerate(categorias_ordem)}

cores_map = {
    'Soberania Plena':        '#1E7E34',  # Verde Floresta
    'Soberania Resiliente':   '#0056B3',  # Azul Marinho
    'Soberania Condicionada': '#F77F00',  # Laranja Âmbar
    'Soberania Tutelada':     '#D90429'   # Vermelho Carmesim
}

# ==============================================================================
# CONSTRUÇÃO GRÁFICA
# ==============================================================================
plt.figure(figsize=(15.5, 9.5), dpi=300)

plt.axvline(x=45, color='gray', linestyle=':', linewidth=1.0, alpha=0.5)
plt.axhline(y=45, color='gray', linestyle=':', linewidth=1.0, alpha=0.5)

# Coordenadas calibradas individualmente para eliminar sobreposições de rótulos
anotacoes = {
    'Estados Unidos':  {'xytext': (93, 103), 'arrow': True},
    'China':           {'xytext': (86, 92),  'arrow': True},
    'Rússia':          {'xytext': (68, 104), 'arrow': True},
    'França':          {'xytext': (82, 82),  'arrow': True},
    'Reino Unido':     {'xytext': (84, 72),  'arrow': True},
    'Índia':           {'xytext': (63, 68),  'arrow': True},

    'Coreia do Norte': {'xytext': (31, 60),  'arrow': True},
    'Paquistão':       {'xytext': (31, 51),  'arrow': True},
    'Irã':             {'xytext': (24, 40),  'arrow': True},

    'Coreia do Sul':   {'xytext': (36, 26),  'arrow': True},
    'Suíça':           {'xytext': (2, 8),    'arrow': False},
    'Turquia':         {'xytext': (31, 20),  'arrow': True},
    'Polônia':         {'xytext': (16, 22),  'arrow': True},

    'Suécia':          {'xytext': (42, 35),  'arrow': True},
    'Brasil':          {'xytext': (19, 13),  'arrow': True},
    'Arábia Saudita':  {'xytext': (9, -3),   'arrow': False},
    'Argentina':       {'xytext': (14, 3),   'arrow': True}
}

for i, nome in enumerate(nomes):
    cid = clusters[i]
    rotulo = cluster_para_rotulo[cid]
    cor = cores_map[rotulo]
    x_val = X_plot[i, 0]
    y_val = X_plot[i, 1]

    plt.scatter(x_val, y_val, c=cor, s=180, edgecolors='black', linewidth=1.2, zorder=5)

    cfg = anotacoes[nome]
    if cfg['arrow']:
        plt.annotate(
            nome,
            xy=(x_val, y_val),
            xytext=cfg['xytext'],
            fontsize=9.5,
            fontweight='bold',
            arrowprops=dict(arrowstyle='->', color='black', lw=0.8, alpha=0.7),
            bbox=dict(boxstyle='round,pad=0.2', facecolor='white', alpha=0.85, edgecolor='none')
        )
    else:
        plt.annotate(
            nome,
            xy=(x_val, y_val),
            xytext=cfg['xytext'],
            fontsize=9.5,
            fontweight='bold',
            bbox=dict(boxstyle='round,pad=0.2', facecolor='white', alpha=0.85, edgecolor='none')
        )

# Centróides K-Means reprojetados no espaço de coordenadas original
for c_scaled in kmeans.cluster_centers_:
    c_orig = scaler.inverse_transform(c_scaled.reshape(1, -1))[0]
    plt.scatter(c_orig[0], c_orig[1], marker='X', s=140, c='black', alpha=0.75, zorder=6)

plt.scatter([], [], marker='X', s=100, c='black', alpha=0.75, label='Centróides K-Means')

for rotulo in categorias_ordem:
    plt.scatter([], [], c=cores_map[rotulo], label=rotulo, s=140, edgecolors='black')

plt.title('Matriz de Soberania Fática vs. Autonomia Dissuasória (ISF 88/12 - K-Means)',
          fontsize=13, fontweight='bold', pad=15)
plt.xlabel('Índice de Soberania Fática - ISF (Dissuasão 88% + Base Civil WIPO 12%)',
           fontsize=11, fontweight='bold')
plt.ylabel('Autonomia Militar Dissuasória Direta (%) [Núcleo Crítico / 0,88]',
           fontsize=11, fontweight='bold')

plt.xlim(-5, 110)
plt.ylim(-6, 112)
plt.grid(True, linestyle='--', alpha=0.5)
plt.legend(title='Estatuto Jurídico-Estratégico', loc='lower right', frameon=True, fontsize=10)
plt.tight_layout()

plt.show()