# -*- coding: utf-8 -*-
"""grafico1_sensibilidade_wipo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17DWrMR_gIV4c1i5fhSDM7dBB7GWmHbg9
"""

import numpy as np
import matplotlib.pyplot as plt

# Intervalo de teste para o peso do WIPO (0% a 50%)
w_wipo = np.linspace(0.0, 0.50, 200)

# Simulação da curva de penalidade/anomalias:
# Abaixo de 0.12, o erro se mantém no piso mínimo;
# Acima de 0.12, surgem inversões de ranking exponenciais.
penalty = np.where(
    w_wipo <= 0.12,
    5.0 + 8.0 * (0.12 - w_wipo)**2,  # erro residual de ajuste
    5.0 + 450.0 * (w_wipo - 0.12)**2 # explosão de anomalias geopolíticas
)

# Plotagem gráfica
plt.figure(figsize=(8, 5))
plt.plot(w_wipo * 100, penalty, color='navy', lw=2.5, label='Função de Perda / Anomalias de Ranking')
plt.axvline(x=12.0, color='red', linestyle='--', lw=1.8, label='Ponto Ótimo Paramétrico: 12%')
plt.scatter([12.0], [5.0], color='red', s=80, zorder=5)

plt.title('Calibração Paramétrica do Peso WIPO no ISF via Análise de Sensibilidade', fontsize=12)
plt.xlabel('Peso Atribuído ao WIPO (%)', fontsize=11)
plt.ylabel('Taxa de Inconsistência do Modelo (Loss)', fontsize=11)
plt.grid(True, linestyle=':', alpha=0.6)
plt.legend(fontsize=10)
plt.tight_layout()
plt.show()