# -*- coding: utf-8 -*-
"""gráfico_03_ahp_pesos_faticos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MnWaXzHHrhbBADPJbzqUqDkMB67WxvYs
"""

"""
Script 3: Partição da Reserva Fática via Processo de Hierarquia Analítica (AHP)
Autor: Guilherme Fontenelle Ribeiro de Oliveira
Descrição:
Aplica o Analytic Hierarchy Process (Saaty, 1980) para derivar formalmente os pesos
relativos dos três subvetores do Núcleo Militar Dissuasório (88%) com base no limiar
perceptual discreto (Weber-Fechner) e na consistência axiomática de Perron-Frobenius.
"""

import numpy as np

# 1. Parâmetros Modulares de Entrada (Precedência Qualitativa Doutrinária)
# Delta = 0.10: limiar mínimo estável de discriminação perceptiva na escala contínua
p_prop_nuc = 1.10   # C2 supera C1 em 10% (Precedência tática cotidiana vs. existencial)
p_nuc_esp  = 1.20   # C1 supera C3 em 20% (Hiato ontológico: sobrevivência vs. precisão)
p_prop_esp = p_prop_nuc * p_nuc_esp  # Transitividade axiomática estrita (1.32)

# 2. Construção Algébrica da Matriz Pareada Recíproca A (Ordem: [Nuclear, Propulsão/Lógica, Espaço])
# A matriz assegura a condição de Saaty: a_ii = 1 e a_ji = 1 / a_ij
A = np.array([
    [1.0,           1.0 / p_prop_nuc,  p_nuc_esp],
    [p_prop_nuc,    1.0,               p_prop_esp],
    [1.0 / p_nuc_esp, 1.0 / p_prop_esp, 1.0]
], dtype=np.float64)

# 3. Extração do Autovetor Principal (Teorema de Perron-Frobenius)
autovalores, autovetores = np.linalg.eig(A)
max_idx = np.argmax(np.real(autovalores))
lambda_max = np.real(autovalores[max_idx])

# Normalização estocástica do autovetor (Pesos Locais w_local)
w_local = np.real(autovetores[:, max_idx])
w_local = w_local / np.sum(w_local)

# 4. Verificação de Consistência Formal de Saaty
n = 3
CI = (lambda_max - n) / (n - 1)
RI = 0.58  # Índice Randômico tabelado por Saaty para n = 3
CR = CI / RI

# 5. Ponderação Global sobre a Reserva Fática Militar (0.88 travada via Grid Search)
w_fatica = np.round(w_local * 0.88, 2)

# 6. Saída Formatada de Auditoria
print("==========================================================")
print("AUDITORIA AHP - RESERVA FÁTICA MILITAR (ISF)")
print("==========================================================")
print(f"Maior Autovalor (lambda_max) : {lambda_max:.6f}")
print(f"Índice de Consistência (CI)   : {CI:.6f}")
print(f"Razão de Consistência (CR)    : {CR:.4f} (Consistência perfeita: CR < 0.10)")
print("----------------------------------------------------------")
print(f"Pesos Locais Normalizados (w) : Nuclear = {w_local[0]:.4f} ({w_local[0]*100:.2f}%)")
print(f"                                Propulsão = {w_local[1]:.4f} ({w_local[1]*100:.2f}%)")
print(f"                                Espaço    = {w_local[2]:.4f} ({w_local[2]*100:.2f}%)")
print("----------------------------------------------------------")
print(f"Pesos Globais Fáticos (88%)  : Nuclear   = {w_fatica[0]:.2f} (30%)")
print(f"                                Propulsão = {w_fatica[1]:.2f} (33%)")
print(f"                                Espaço    = {w_fatica[2]:.2f} (25%)")
print(f"Soma Total do Bloco Militar   : {np.sum(w_fatica):.2f} (0.88)")
print("==========================================================")